import type { LedgerState } from "./types";

export const DEMO_STATE: LedgerState = {
  settings: {
    companyName: "مؤسسة النور للتشطيبات",
    ownerName: "محمود عبد الرحمن",
    phone: "01023456789",
    openingCapital: 180000,
    currency: "EGP",
  },
  customers: [
    {
      id: "c_ahmed",
      name: "أحمد محمود السيد",
      phone: "01098765432",
      address: "التجمع الخامس، القاهرة الجديدة",
      notes: "عميل شقة كاملة التشطيب",
      createdAt: "2026-01-12",
    },
    {
      id: "c_fatima",
      name: "فاطمة حسن علي",
      phone: "01234567890",
      address: "الساحل الشمالي، سيدي عبد الرحمن",
      notes: "فيلا صيفي — تشطيب فاخر",
      createdAt: "2026-03-04",
    },
    {
      id: "c_amal",
      name: "شركة الأمل العقارية",
      phone: "0225678901",
      address: "مدينة نصر، شارع عباس العقاد",
      notes: "محل تجاري دور أرضي",
      createdAt: "2026-05-20",
    },
  ],
  projects: [
    {
      id: "p_tagamoa",
      customerId: "c_ahmed",
      name: "شقة 120م — التجمع الخامس",
      location: "كمبوند ليان، التجمع الخامس",
      contractAmount: 420000,
      startDate: "2026-02-01",
      status: "in_progress",
      notes: "تشطيب كامل: سباكة، كهرباء، أرضيات، دهانات، مطبخ.",
      createdAt: "2026-01-18",
    },
    {
      id: "p_sahel",
      customerId: "c_fatima",
      name: "فيلا الساحل الشمالي",
      location: "سيدي عبد الرحمن، الكيلو 134",
      contractAmount: 890000,
      startDate: "2026-03-15",
      status: "in_progress",
      notes: "تشطيب الواجهات والحديقة والطابق الأرضي.",
      createdAt: "2026-03-08",
    },
    {
      id: "p_nasr",
      customerId: "c_amal",
      name: "محل تجاري — مدينة نصر",
      location: "عباس العقاد، مدينة نصر",
      contractAmount: 175000,
      startDate: "2026-06-01",
      status: "completed",
      notes: "تسليم تم في أغسطس. ضمان سنة على الكهرباء.",
      createdAt: "2026-05-22",
    },
  ],
  payments: [
    {
      id: "pay_1",
      projectId: "p_tagamoa",
      amount: 120000,
      date: "2026-02-03",
      method: "bank",
      notes: "دفعة تعاقد",
    },
    {
      id: "pay_2",
      projectId: "p_tagamoa",
      amount: 90000,
      date: "2026-05-11",
      method: "cash",
      notes: "بعد السباكة والكهرباء",
    },
    {
      id: "pay_3",
      projectId: "p_sahel",
      amount: 250000,
      date: "2026-03-18",
      method: "bank",
      notes: "دفعة أولى",
    },
    {
      id: "pay_4",
      projectId: "p_sahel",
      amount: 180000,
      date: "2026-07-02",
      method: "cheque",
      notes: "شيك شهر يوليو",
    },
    {
      id: "pay_5",
      projectId: "p_nasr",
      amount: 80000,
      date: "2026-06-04",
      method: "bank",
      notes: "تعاقد",
    },
    {
      id: "pay_6",
      projectId: "p_nasr",
      amount: 95000,
      date: "2026-08-20",
      method: "wallet",
      notes: "دفعة التسليم",
    },
  ],
  expenses: [
    {
      id: "ex_1",
      projectId: "p_tagamoa",
      category: "materials",
      amount: 64000,
      date: "2026-02-10",
      vendor: "معرض السيراميك الحديث",
      notes: "أرضيات حمامات ومطبخ",
    },
    {
      id: "ex_2",
      projectId: "p_tagamoa",
      category: "labor",
      amount: 38000,
      date: "2026-04-02",
      vendor: "مقاول العمالة اليومية",
      notes: "محارة ودهان",
    },
    {
      id: "ex_3",
      projectId: "p_sahel",
      category: "materials",
      amount: 145000,
      date: "2026-04-12",
      vendor: "شركة الرخام المصري",
      notes: "رخام الواجهة والسلالم",
    },
    {
      id: "ex_4",
      projectId: "p_sahel",
      category: "transport",
      amount: 18000,
      date: "2026-04-14",
      vendor: "نقل مواد الساحل",
      notes: "نقل رخام للساحل",
    },
    {
      id: "ex_5",
      projectId: "p_nasr",
      category: "materials",
      amount: 42000,
      date: "2026-06-08",
      vendor: "تشطيبات النور — مخزن",
      notes: "جبس بورد وإضاءة",
    },
    {
      id: "ex_6",
      projectId: "p_nasr",
      category: "labor",
      amount: 27000,
      date: "2026-07-15",
      vendor: "ورشة التشطيب",
      notes: "عمالة المحل",
    },
    {
      id: "ex_7",
      projectId: null,
      category: "rent",
      amount: 24000,
      date: "2026-01-05",
      vendor: "مالك المخزن",
      notes: "إيجار مخزن الربع الأول",
    },
    {
      id: "ex_8",
      projectId: null,
      category: "tools",
      amount: 9600,
      date: "2026-03-01",
      vendor: "عدة البناء",
      notes: "شنيور وعدة كهرباء",
    },
  ],
};

export const EMPTY_STATE: LedgerState = {
  settings: {
    companyName: "شركتي للمقاولات",
    ownerName: "",
    phone: "",
    openingCapital: 0,
    currency: "EGP",
  },
  customers: [],
  projects: [],
  payments: [],
  expenses: [],
};
